config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "orders#new"
  resources :orders
  resources :items, only: [:new, :create, :index, :destroy]
  resources :discounts, only: [:new, :create, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discount.rb
# frozen_string_literal: true

class Discount < ApplicationRecord
  belongs_to :item
  belongs_to :applicable_item, class_name: "Item", foreign_key: :applicable_item_id, optional: true

  validates :item_id, presence: true
  validates :discount_rate, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :self_discounts, -> {
    where(applicable_item: nil)
  }

  scope :deal_discounts, -> {
    where.not(applicable_item: nil)
  }

  def apply_on_associated_item?
    applicable_item.present?
  end

  def calculate_discount(price)
    discount_amount = (price * discount_rate) / 100

    allowed_discount_amount(discount_amount)
  end

  def allowed_discount_amount(discount_amount)
    return discount_amount if cap_amount.nil? # no cap limit apply

    [discount_amount, cap_amount].min
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  has_many :discounts, dependent: :destroy
  has_many :deal_discounts, class_name: "Discount", foreign_key: :applicable_item_id, dependent: :destroy
  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :tax_rate, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  def all_discounts
    discounts.self_discounts + deal_discounts
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  include AASM

  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  validates :customer_name, :customer_contact, :order_type, presence: true
  validate :at_least_one_order_item

  accepts_nested_attributes_for :order_items

  enum order_type: {
    dine_in: 'Dine In',
    take_away: 'Take Away'
  }


  aasm column: :state do
    state :pending, initial: true
    state :processing
    state :complete

    event :process do
      transitions from: :pending, to: :processing
      after do
        notify_order
      end
    end

    event :completed do
      transitions from: :processing, to: :complete
      after do
        notify_order
      end
    end
  end

  def at_least_one_order_item
    return true if order_items.any?

    errors.add :order_items, "Atleast one item should exists"

    false
  end

  def scheduled_jobs
    OrderProcessWorker.perform_in(10.seconds, id)
    OrderCompletedWorker.perform_in(20.seconds, id)
  end

  def notify_order
    ActionCable.server.broadcast('order_creation_channel', { id: id, state: state.titleize,  message: "Order No# #{id} is #{state}" })
  end
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :quantity, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  protect_from_forgery with: :null_session
end

app/controllers/discounts_controller.rb
# frozen_string_literal: true

class DiscountsController < ApplicationController

  def index
    @discounts = Discount.all    
    respond_to do |format|
      format.html # Render HTML template (if needed)
      format.json { render json: @discounts }
    end
  end

  def new
    @discount = Discount.new
  end

  def create
    @discount = Discount.new(discount_params)
    respond_to do |format|
      if @discount.save
        format.html { redirect_to discounts_path, notice: "Discount was successfully created." }
        format.json { render json: @discount }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discount = Discount.find(params[:id])

    respond_to do |format|
      if @discount.destroy
        format.html { redirect_to discounts_path, notice: 'Discount deleted successfully.' }
        format.json { render json: { message: 'Discount deleted successfully.' }, status: :ok }
      else
        format.html { redirect_to discounts_path, alert: "Failed to delete Discount." }
        format.json { render json: { errors: @discount.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private

  def discount_params
    params.require(:discount).permit(:item_id, :applicable_item_id, :discount_rate, :cap_amount)
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController

  def index
    @items = Item.all    
    respond_to do |format|
      format.html # Render HTML template (if needed)
      format.json { render json: @items }
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: "Item was successfully created." }
        format.json { render json: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.orders.none? && @item.destroy
        format.html { redirect_to items_path, notice: 'Item deleted successfully.' }
        format.json { render json: { message: 'Item deleted successfully.' }, status: :ok }
      else
        format.html { redirect_to items_path, alert: "Failed to delete item. #{@item.orders.count} attached orders" }
        format.json { render json: { errors: @item.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :tax_rate)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController

  def index
    @pagy, @orders = pagy(Order.order(id: :desc).all, items: 10)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items    
  end

  def new
    @order = Order.new
    @items = Item.all
  end

  def create
    @items = Item.all
    @order = Orders::OrderService.placeOrder(order_params)

    respond_to do |format|
      if @order.persisted?
        @order.scheduled_jobs

        format.html { redirect_to orders_path, notice: "Order was successfully created." }
        format.json { render json: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.destroy
        format.html { redirect_to orders_path, notice: 'Order deleted successfully.' }
        format.json { render json: { message: 'Order deleted successfully.' }, status: :ok }
      else
        format.html { redirect_to orders_path, alert: "Failed to delete order." }
        format.json { render json: { errors: @order.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_name, :customer_contact, :order_type, order_items_attributes: [:quantity, :item_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/discounts/index.html.erb
<div class="container mt-4">
  <h1>Discounts</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Item</th>
        <th>Applicable Item</th>
        <th>Discount Rate</th>
        <th>Cap Amount</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @discounts.each do |discount| %>
        <tr>
          <td><%= discount.item.name.titleize %></td>
          <td><%= discount.applicable_item&.name&.titleize || 'N/A' %></td>
          <td><%= discount.discount_rate %></td>
          <td><%= discount.cap_amount %></td>
          <td><%= button_to "Delete", discount_path(discount), method: :delete, data: { confirm: 'Are you sure you want to delete this discount?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <a class="btn btn-secondary" href="/discounts/new">Create Discount</a>
  </div>
</div>

app/views/discounts/new.html.erb
<div class="container mt-4">
  <h1>New Discount</h1>
  <%= form_with(model: @discount, url: discounts_path, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :item_id, class: "form-label" %>
      <%= form.select :item_id, Item.pluck(:name, :id), { prompt: "Select Item" }, class: "form-select" %>
      <% if @discount.errors.has_key?(:item_id) %>
        <p class="text-danger">
          <%= @discount.errors[:item_id].first %>
        </p>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :applicable_item_id, class: "form-label" %>
      <%= form.select :applicable_item_id, Item.pluck(:name, :id), { prompt: "Select Applicable Item" }, class: "form-select" %>
      <% if @discount.errors.has_key?(:applicable_item_id) %>
        <p class="text-danger">
          <%= @discount.errors[:applicable_item_id].first %>
        </p>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :discount_rate, class: "form-label" %>
      <%= form.number_field :discount_rate, step: "0.01", class: "form-control" %>
      <% if @discount.errors.has_key?(:discount_rate) %>
        <p class="text-danger">
          <%= @discount.errors[:discount_rate].first %>
        </p>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :cap_amount, class: "form-label" %>
      <%= form.number_field :cap_amount, step: "0.01", class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.submit "Create Discount", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/items/index.html.erb
<!-- views/items/index.html.erb -->
<div class="container mt-4">
  <h1>Items</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Tax Rate</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= number_to_currency(item.price) %></td>
          <td><%= number_to_percentage(item.tax_rate, precision: 2) %></td>
          <td><%= button_to "Delete", item_path(item), method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <a class="btn btn-secondary" href="/items/new">Create Item</a>
  </div>
</div>

app/views/items/new.html.erb
<div class="container mt-4">
  <h3>Create New Item</h3>
  <%= form_with model: @item, url: items_path, class: "form-control m-3 w-50" do |form| %>
    <div>
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
      <% if @item.errors.has_key?(:name) %>
        <p class="text-danger">
          <%= @item.errors[:name].first %>
        </p>
      <% end %>
    </div>
    <div>
      <%= form.label :price, class: "form-label" %>
      <%= form.number_field :price, step: "0.01", class: "form-control" %>
      <% if @item.errors.has_key?(:price) %>
        <p class="text-danger">
          <%= @item.errors[:price].first %>
        </p>
      <% end %>
    </div>
    <div>
      <%= form.label :tax_rate, class: "form-label" %>
      <small>(Tax rate should greater than 0 and less than 100)</small>
      <%= form.number_field :tax_rate, step: "0.01", class: "form-control" %>
      <% if @item.errors.has_key?(:tax_rate) %>
        <p class="text-danger">
          <%= @item.errors[:tax_rate].first %>
        </p>
      <% end %>
    </div>

    <div class="m-2">
      <%= form.submit "Create Item", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeehub</title>
  <!-- Add meta tags, favicon, etc. -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Add Bootstrap CSS -->
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <!-- Add your custom CSS here (if any) -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <!-- Create the navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Navbar brand or logo (if you have one) -->
      <a class="navbar-brand" href="/">Coffee Hub</a>

      <!-- Navbar items -->
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/orders/new">Create Order</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/discounts">Discounts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items">Items</a>
        </li>
      </ul>
    </div>
  </nav>
  <% if flash[:notice].present? %>
    <div id="flash-message" class="alert alert-success m-2">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert].present? %>
    <div id="flash-message" class="alert alert-danger m-2">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <!-- Yield the content of the views -->
  <div id="app" class="container mt-4">
    <%= yield %>
  </div>

</body>
<script>
  document.addEventListener('DOMContentLoaded', () => {
    const flashMessage = document.getElementById('flash-message');

    // Function to remove the flash message after 10 seconds
    const removeFlashMessage = () => {
      if (flashMessage) {
        flashMessage.remove();
      }
    };

    // Set a timer to remove the flash message after 10 seconds
    setTimeout(removeFlashMessage, 10000); // 10000 milliseconds = 10 seconds
  });
</script>
</html>

app/views/orders/_order_row.html.erb
<tr>
  <td class="text-bg-dark" colspan="3"><b>Total</b></td>
  <td class="text-bg-dark"><%= number_to_currency(order.price) %></td>
  <td class="text-bg-dark"><%= number_to_currency(order.discount) %></td>
  <td class="text-bg-dark"><%= number_to_currency(order.taxable_amount) %></td>
  <td class="text-bg-dark"><%= number_to_currency(order.payable) %></td>
</tr>

app/views/orders/index.html.erb
<div class="container mt-4">
  <h1>Orders</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Customer Name</th>
        <th>Customer Contact</th>
        <th>Order Type</th>
        <th>State</th>
        <th>Price</th>
        <th>Discount</th>
        <th>Payable</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.customer_name.titleize %></td>
          <td><%= order.customer_contact %></td>
          <td><%= Order.order_types[order.order_type] %></td>
          <td id="<%= "order-state-#{order.id}"%>"><%= order.state.titleize %></td>
          <td><%= number_to_currency(order.price) %></td>
          <td><%= number_to_currency(order.discount) %></td>
          <td><%= number_to_currency(order.payable) %></td>
          <td><%= link_to 'View Items', order_path(order), class: "btn btn-secondary" %></td>
          <td><%= button_to "Delete", order_path(order), method: :delete, data: { confirm: 'Are you sure you want to delete this order?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/orders/new.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= action_cable_meta_tag %>
<div>
  <h3>Place a Order</h3>
</div>
<%= form_with model: @order, url: orders_path, class: "form-control m-3 w-50" do |form| %>
  <div>
    <%= form.label :customer_name, class: "form-label" %>
    <%= form.text_field :customer_name, class: "form-control" %>
    <% if @order.errors.has_key?(:customer_name) %>
      <p class="text-danger">
        <%= @order.errors[:customer_name].first %>
      </p>
    <% end %>
  </div>
  <div>
    <%= form.label :customer_contact, class: "form-label" %>
    <%= form.text_field :customer_contact, class: "form-control" %>
    <% if @order.errors.has_key?(:customer_contact) %>
      <p class="text-danger">
        <%= @order.errors[:customer_contact].first %>
      </p>
    <% end %>
  </div>
  <div>
    <%= form.label :order_type, class: "form-label" %>
    <%= form.select :order_type, Order.order_types.values, {}, {:class => "form-select"} %>
    <% if @order.errors.has_key?(:order_type) %>
      <p class="text-danger">
        <%= @order.errors[:order_type].first %>
      </p>
    <% end %>
  </div>

  <div>
    <h3 class="m-2">Order Items</h3>
    <table class="table m-1">
      <thead>
        <tr>
          <th>Item</th>
          <th>Quantity</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% if @order.order_items.any? %>
          <% @order.order_items.each do |order_item| %>
            <tr>
              <td>
                <%= select_tag "order[order_items_attributes][][item_id]", options_for_select(@items.map { |item| [item.name, item.id] }, order_item.item_id), class: "form-select" %>
              </td>
              <td>
                <%= number_field_tag "order[order_items_attributes][][quantity]", order_item.quantity, class: "form-control" %>
              </td>
              <td><a class="btn btn-danger remove-checkbox" onclick="removeItem()" >Remove</a></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <% if @order.errors.has_key?(:order_items) %>
      <p class="text-danger">
        <%= @order.errors[:order_items].first %>
      </p>
    <% elsif @order.errors.has_key?(:"order_items.quantity") %>
      <p class="text-danger">
        <%= @order.errors[:"order_items.quantity"] %>
      </p>
    <% end %>
  </div>

  <div class="m-2">
    <a class="add-item btn btn-secondary" onclick="addItemClicked()">Add Item</a>
  </div>
  <hr>

  <div class="m-1">
    <%= form.submit "Create Order", class: "btn btn-primary" %>
  </div>
<% end %>

<script>  
  function addItemClicked() {
    const orderItemsTable = document.querySelector('table > tbody');

    const newRow = document.createElement('tr');
    newRow.innerHTML = `
      <td>
        <select name="order[order_items_attributes][][item_id]" class="form-select">
          <option value="">Select Item</option>
          <% @items.each do |item| %>
            <option value="<%= item.id %>"><%= item.name %></option>
          <% end %>
        </select>
      </td>
      <td><input type="number" name="order[order_items_attributes][][quantity]" class="form-control" /></td>
      <td><a class="btn btn-danger remove-checkbox" onclick="removeItem()">Remove</a></td>
    `;
    orderItemsTable.appendChild(newRow);
  }
  function removeItem() {
    const orderItemsTable = document.querySelector('table > tbody');

    orderItemsTable.addEventListener('click', (e) => {
      if (e.target.classList.contains('remove-checkbox')) {
        const row = e.target.closest('tr');
        row.remove();
      }
    });
  }
</script>

app/views/orders/show.html.erb
<div class="container mt-4">

  <h4>Order</h4>
  <div class="d-flex">
    <div class="m-2 fw-bold">
      <p>id:</p>
      <p>State:</p>
    </div>
    <div class="m-2">
      <p> <%= @order.id %></p>
      <p id="<%= "order-state-#{@order.id}"%>"> <%= @order.state %></p>      
    </div>
  </div>
  <h4>Order Items</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Sr</th>
        <th>Item</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Discount</th>
        <th>Taxable Amount</th>
        <th>Payable</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each_with_index do |item, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= item.item.name.titleize %></td>
          <td><%= item.quantity %></td>
          <td><%= number_to_currency(item.price) %></td>
          <td><%= number_to_currency(item.discount) %></td>
          <td><%= number_to_currency(item.taxable_amount) %></td>
          <td><%= number_to_currency(item.payable) %></td>
        </tr>
      <% end %>
      <%= render 'order_row', order: @order %>
    </tbody>
  </table>
</div>